#!/usr/bin/php
<?php
use Charon\CLI;
require_once('system/libs/puck/puck.php');
Puck::init(1);
CLI::init(function(){
  CLI::command('', function(){
    CLI::line();
    CLI::out('Charon Console 1.0.0', CLI_CENTER);
    CLI::out('--------------------', CLI_CENTER);
    CLI::eol();
    CLI::line();
  });
}, $argv);
